SELECT COUNT(*) AS active_users_count FROM SEC_USER WHERE USR_ACTIVE_IND = 'Y';

SELECT * FROM (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY USR_UID ORDER BY MR_CREATED_DT DESC) AS row_num
  FROM MEDICAL_RECORD
) AS ranked_records
WHERE row_num = 1;

SELECT u.*, p.*, m.*
FROM SEC_USER u
LEFT JOIN PRESCRIPTION_RECORD p ON u.USR_UID = p.USR_UID
LEFT JOIN MEDICINES m ON p.MEDICINE_UID = m.MEDICINE_UID;

SELECT m.*, u.USR_FNAME, u.USR_LNAME, a.*
FROM MEDICAL_RECORD m
LEFT JOIN SEC_USER u ON m.USR_UID = u.USR_UID
LEFT JOIN APPOINTMENTS a ON m.USR_UID = a.USR_UID;

SELECT a.*, u.USR_FNAME AS patient_fname, u.USR_LNAME AS patient_lname, d.USR_FNAME,
       p.PR_UID, m.MEDICINE_NAME, p.DOSAGE, p.FREQUENCY
FROM APPOINTMENTS a
LEFT JOIN SEC_USER u ON a.USR_UID = u.USR_UID
LEFT JOIN SEC_USER d ON a.USR_UID = d.USR_UID AND d.USR_TYPE = 'D'
LEFT JOIN PRESCRIPTION_RECORD p ON a.USR_UID = p.USR_UID
LEFT JOIN MEDICINES m ON p.MEDICINE_UID = m.MEDICINE_UID;

SELECT h.*, u.USR_FNAME, u.USR_LNAME, a.APP_DATE, a.APP_TIME
FROM HEALTH_MATRIX h
LEFT JOIN SEC_USER u ON h.USR_UID = u.USR_UID
LEFT JOIN APPOINTMENTS a ON h.USR_UID = a.USR_UID;

SELECT U.*
FROM SEC_USER U
INNER JOIN USER_ROLE_MAPPING UR ON U.USR_UID = UR.USER_ID
INNER JOIN SEC_USER_ROLES R ON UR.ROLE_ID = R.SEC_USR_ROLE_UID
WHERE R.SEC_USR_ROLE_NAME = 'Doctor';