-- Create a new table
CREATE TABLE HEALTH_MATRIX (
    METRIC_UID INT PRIMARY KEY AUTO_INCREMENT,
    USR_UID INT,
    DEVICE_UID INT,
    METRIC_DATE DATE,
    APP_TIME TIME,
    METRIC_TYPE VARCHAR(255),
    METRIC_VALUE DECIMAL(10, 2),
    METRIC_UNIT VARCHAR(50),
    METRIC_NOTES TEXT,
    LOCATION VARCHAR(100),
    METRIC_QUALITY VARCHAR(50),
    METRIC_CONTEXT VARCHAR(100),
    IS_MANUAL_ENTRY BOOLEAN,
    IS_VERIFIED BOOLEAN,
    METRIC_LST_MODIFY_DT TIMESTAMP,
    METRIC_LST_MODIFY_BY VARCHAR(255),
    METRIC_CREATED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    METRIC_CREATED_BY VARCHAR(255),
    FOREIGN KEY (USR_UID) REFERENCES SEC_USER(USR_UID),
    FOREIGN KEY (DEVICE_UID) REFERENCES DEVICES(DEVICE_UID)
);

-- Insert data into the table  

-- Retrive data from the table based on conditions

-- Update data from the table 

-- Delete data from the table 




