-- Create a new table
CREATE TABLE PRESCRIPTION_RECORD (
    PR_UID INT PRIMARY KEY AUTO_INCREMENT,
    USR_UID INT,
    MEDICINE_UID INT,
    DOSAGE VARCHAR(255),
    FREQUENCY VARCHAR(255),
    PR_VALIDITY DATE,
    PR_LST_MODIFY_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PR_LST_MODIFY_BY VARCHAR(255),
    PR_CREATED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PR_CREATED_BY VARCHAR(255),
    FOREIGN KEY (USR_UID) REFERENCES SEC_USER (USR_UID),
    FOREIGN KEY (MEDICINE_UID) REFERENCES MEDICINES (MEDICINE_UID)
);

-- Insert data into the table  
INSERT INTO PRESCRIPTION_RECORD (USR_UID, MEDICINE_UID, DOSAGE, FREQUENCY, PR_VALIDITY, PR_LST_MODIFY_BY, PR_CREATED_BY) VALUES
(201, 1, '500mg', 'Twice daily', '2024-05-31', 'admin', 'admin'),
(202, 2, '250mg', 'Once daily', '2024-06-15', 'admin', 'admin'),
(205, 4, '50mg', 'Once daily', '2024-07-15', 'admin', 'admin'),
(206, 5, '10mg', 'Once daily', '2024-08-01', 'admin', 'admin');

-- Retrive data from the table based on conditions
SELECT * FROM PRESCRIPTION_RECORD;
SELECT * FROM PRESCRIPTION_RECORD WHERE CAST(DOSAGE AS DECIMAL) > 100;
SELECT * FROM PRESCRIPTION_RECORD WHERE PR_VALIDITY >= CURDATE();


-- Update data from the table 
UPDATE PRESCRIPTION_RECORD 
SET MEDICINE_UID = 7 
WHERE PR_UID = 1;

-- Delete data from the table 
DELETE FROM PRESCRIPTION_RECORD 
WHERE PR_UID = 13;




