-- Create a new table
CREATE TABLE USER_ROLE_MAPPING (
    USER_ID INT,
    ROLE_ID INT,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES SEC_USER(USR_UID),
    FOREIGN KEY (ROLE_ID) REFERENCES SEC_USER_ROLES(SEC_USR_ROLE_UID)
);

-- Insert data into the table 
INSERT INTO USER_ROLE_MAPPING (USER_ID, ROLE_ID) VALUES
(101, 1), 
(201, 4), 
(501, 2), 
(701, 3); 

INSERT INTO USER_ROLE_MAPPING (USER_ID, ROLE_ID) VALUES
(202, 4), 
(203, 4), 
(204, 4), 
(205, 4),
(206, 4);

INSERT INTO USER_ROLE_MAPPING (USER_ID, ROLE_ID) VALUES 
(702, 3),
(703, 3);

INSERT INTO USER_ROLE_MAPPING (USER_ID, ROLE_ID) VALUES 
(502, 2),
(503, 2),
(504, 2),
(505, 2);


-- Retrive data from the table based on conditions
SELECT * FROM USER_ROLE_MAPPING;